# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-24 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='updated_at',
        ),
    ]
